name: ex14_sol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - requests=2.32.5
  - pip=24.3.1
  - mlflow=3.2.0
  - hydra-core=1.3.2
  - scikit-learn=1.7.2
  - pandas=2.3.2
  - pip:
      - wandb==0.21.3
      - hydra-joblib-launcher==1.2.0
