name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.32.3
  - pip=24.3.1
  - mlflow=2.18.0
  - hydra-core=1.3.2
  - pip:
      - wandb==0.18.7
      - hydra-joblib-launcher==1.2.0
