name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - requests=2.32.5
  - pip=24.3.1
  - pandas=2.3.1
  - scikit-learn=1.7.2
  - mlflow=2.18.0
  - pip:
      - wandb==0.22.0