name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests=2.24.0
  - pip=23.3.1
  - seaborn=0.13.2
  - pandas=2.2.1
  - scikit-learn=1.4.1
  - matplotlib==3.8.3
  - pillow=10.2.0
  - pip:
      - wandb==0.16.4